import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { PokeList } from '../components/PokeList'
import { PokeOptions } from '../components/PokeOptions'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <section>
        <PokeList/>
        <PokeOptions/>
      </section>
    </div>
  )
}
